# Set quick access app icons
fav_apps: "['firefox.desktop', 'chromium.desktop', 'brave-browser.desktop', 'org.gnome.Nautilus.desktop', 'nvim.desktop', 'codium.desktop', 'terminator.desktop', 'bitwarden.desktop']"
# Correct app picker
app_picker: "[{'Utilities': <{'position': <0>}>, 'c9c838d3-8bf4-4ae5-996e-f0dd765927cd': <{'position': <1>}>, 'f986d733-2ecc-4bc4-9153-eed210f68aa1': <{'position': <2>}>, 'io.github.celluloid_player.Celluloid.desktop': <{'position': <3>}>}]"
folder_children: "['Utilities', 'YaST', 'c9c838d3-8bf4-4ae5-996e-f0dd765927cd', 'f986d733-2ecc-4bc4-9153-eed210f68aa1']"
# Folder 1
folder1: "/org/gnome/desktop/app-folders/folders/c9c838d3-8bf4-4ae5-996e-f0dd765927cd"
folder1_apps: "['libreoffice-base.desktop', 'libreoffice-startcenter.desktop', 'libreoffice-calc.desktop', 'libreoffice-draw.desktop', 'libreoffice-math.desktop', 'libreoffice-impress.desktop', 'libreoffice-writer.desktop', 'org.gnome.Calculator.desktop', 'org.gnome.gedit.desktop', 'texmaker.desktop']"
folder1_name: "'Office'"
# Folder 2
folder2: "/org/gnome/desktop/app-folders/folders/f986d733-2ecc-4bc4-9153-eed210f68aa1"
folder2_apps: "['org.gnome.Settings.desktop', 'eos-apps-info.desktop', 'eos-log-tool.desktop', 'eos-update-notifier-configure.desktop', 'welcome.desktop', 'UpdateInTerminal.desktop', 'reflector-simple.desktop', 'eos-quickstart.desktop']"
folder2_name: "'Settings'"
# Folder 3
folder3: "/org/gnome/desktop/app-folders/folders/Utilities"
folder3_apps: "['gnome-abrt.desktop', 'gnome-system-log.desktop', 'nm-connection-editor.desktop', 'org.gnome.baobab.desktop', 'org.gnome.Connections.desktop', 'org.gnome.DejaDup.desktop', 'org.gnome.Dictionary.desktop', 'org.gnome.DiskUtility.desktop', 'org.gnome.eog.desktop', 'org.gnome.Evince.desktop', 'org.gnome.FileRoller.desktop', 'org.gnome.fonts.desktop', 'org.gnome.seahorse.Application.desktop', 'org.gnome.tweaks.desktop', 'org.gnome.Usage.desktop', 'vinagre.desktop', 'bssh.desktop', 'bvnc.desktop', 'avahi-discover.desktop', 'mpv.desktop', 'electron16.desktop', 'org.gnome.Terminal.desktop', 'org.gnome.Extensions.desktop', 'firewall-config.desktop', 'lstopo.desktop', 'org.gnome.meld.desktop', 'yad-icon-browser.desktop', 'uxterm.desktop', 'xterm.desktop', 'pavucontrol.desktop', 'qv4l2.desktop', 'qvidcap.desktop', 'stoken-gui.desktop', 'stoken-gui-small.desktop', 'jshell-java-openjdk.desktop', 'xdvi.desktop', 'gnome-nettool.desktop', 'jconsole-java-openjdk.desktop', 'org.gnome.PowerStats.desktop', 'yad-settings.desktop']"
# Package names
fira_font_package: ttf-fira-code
jre: jre-openjdk
jdk: jdk-openjdk
codium: codium
go: go
rust: rust
