- name: Install chromium
  package:
    name: chromium
    state: latest

- name: Install brave
  flatpak:
    name: com.brave.Browser
    state: present

- name: Download codium
  shell:
    #This one-liner curls a response from github's api, greps the rpm download file link, cleans it up and then uses wget to download the file
    cmd: curl -s https://api.github.com/repos/VSCodium/vscodium/releases/latest | egrep -i '"browser_download_url":.*x86_64.rpm"' | awk '{print $2}' | sed s/\"//g | xargs wget -qO ./codium.rpm

- name: Install codium
  dnf:
    name: ./codium.rpm
    state: present

- name: Remove codium.rpm
  file:
    path: ./codium.prm
    state: absent

- name: Install bitwarden
  flatpak:
    name: com.bitwarden.desktop
    state: present

- name: Install celluloid
  flatpak:
    name: io.github.celluloid_player.celluloid
    state: present
