- name: Install chromium
  package:
    name: chromium
    state: latest

- name: Install brave
  flatpak:
    name: com.brave.Browser
    state: present

- name: Install codium
  flatpak:
    name: com.vscodium.codium
    state: present

- name: Install bitwarden
  flatpak:
    name: com.bitwarden.desktop
    state: present

- name: Install celluloid
  flatpak:
    name: io.github.celluloid_player.celluloid
    state: present
