- name: Install chromium
  package:
    name: chromium
    state: latest

- name: Install yay
  package:
    name: yay
    state: latest

- name: Install brave
  become_user: will
  command: yay -S brave-bin --answerdiff N --answerclean A

- name: Install codium
  become_user: will
  command: yay -S vscodium-bin --answerdiff N --answerclean A

- name: Install bitwarden
  package:
    name: bitwarden
    state: latest
