# Arch------
- name: Clean cache (Arch)
  command: paccache -r
  when: ansible_distribution == "Archlinux"

# SUSE------
- name: Post-install Cleaning (SUSE)
  command: zypper clean
  when: ansible_distribution == "SUSE"

# Ubuntu----
- name: Post-install Cleaning (Ubuntu)
  apt:
    autoclean: yes
    autoremove: yes
  when: ansible_distribution == "Ubuntu"

# Fedora----
- name: Clean dnf (Fedora)
  dnf:
    autoremove: yes
  when: ansible_distriubtion == "Fedora"
#TODO-Maybe: Implement some sort of reporting
