# Get distro vars
- include_vars: "{{ ansible_distribution }}.yml"

# Do updates
- import_tasks: software/update.yml

# Install software
- import_tasks: software/install.yml

# Perform rest of system setup
- import_tasks: setup/setup.yml
