# TODO: Make this not be hardcoded for manjaro laptop, this is supposed to work on e.g. Ubuntu server as well, need var file with package names

# Load our vault variables
- include_vars: vault.yml

# Configure users
- import_tasks: users/will.yml

# Import our sorted mirrors and update syste
- import_tasks: software/update.yml

# Install software
- import_tasks: software/install.yml

# Perform rest of system setup
- import_tasks: setup/setup.yml
