- name: Install systemd-timesyncd (Ubuntu)
  package:
    name: systemd-timesyncd
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Enable and start systemd-timesyncd
  service:
    name: systemd-timesyncd
    enabled: yes
    state: started

- name: Set NTP true
  command: timedatectl set-ntp true
