- name: Create swap file, if doesn't exist
  command: dd if=/dev/zero of=/swapfile bs=1024 count=4096k
           creates=/swapfile

- name: Correct swap permissions
  file:
    path: /swapfile
    owner: root
    group: root
    mode: 0600

- name: Check swap file
  command: file /swapfile
  register: swapfile

- name: Make swap
  command: mkswap /swapfile
  when: swapfile.stdout.find('swap file') == -1

- name: Write swap in fstab
  lineinfile:
    dest: /etc/fstab
    regexp: "/swapfile"
    line: "/swapfile none swap sw 0 0"

- name: Swapon
  command: swapon /swapfile
  when: ansible_swaptotal_mb < 1
