- name: Install Fira Code
  package:
    name: ttf-fira-code
    state: latest

- name: Refresh Fonts
  command: fc-cache -fv

- name: Set Fira Font
  become_user: will
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: "/org/gnome/desktop/interface/font-name", value: "'Fira Code 10'" }
    - { key: "/org/gnome/desktop/interface/document-font-name", value: "'Fira Code 11'" }
    - { key: "/org/gnome/desktop/interface/monospace-font-name", value: "'Fira Code 11'" }

- name: Speed up key repeat delay and speed
  become_user: will
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: "/org/gnome/desktop/peripherals/keyboard/delay", value: "uint32 300" }
    - { key: "/org/gnome/desktop/peripherals/keyboard/repeat-interval", value: "uint32 20" }

- name: Create keybinding locations
  become_user: will
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
    value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/']"

- name: Printscreen hotkeys
  become_user: will
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value}}"
  with_items:
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/area-screenshot", value: "['<Shift>Print']" }
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/area-screenshot-clip", value: "['Print']" }

- name: Files hotkey
  become_user: will
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value}}"
  with_items:
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding", value: "'<Super>e'" }
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command", value: "'/usr/bin/nautilus'" }
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name", value: "'Files'" }

- name: Terminator hotkey
  become_user: will
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value}}"
  with_items:
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding", value: "'<Primary><Alt>t'" }
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command", value: "'/usr/bin/terminator'" }
    - { key: "/org/gnome/settings-daemon/pluginsC/media-keys/custom-keybindings/custom1/name", value: "'Terminator'" }

- name: Caps becomes ctrl (vim)
  become_user: will
  dconf:
    key: "/org/gnome/desktop/input-sources/xkb-options"
    value: "['lv3:ralt_switch', 'caps:ctrl_modifier']"

- name: Maximize hoykey
  become_user: will
  dconf:
    key: "/org/gnome/desktop.wm/keybindings/maximize"
    value: "['<Super>Up']"

- name: Show battery percentage
  become_user: will
  dconf:
    key: "/org/gnome/desktop/interface/show-battery-percentage"
    value: "'true'"

- name: Show week number and week day
  become_user: will
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value}}"
  with_items:
    - { key: "/org/gnome/desktop/calendar/show-weekdate", value: "true" }
    - { key: "/org/gnome/desktop/interface/clock-show-weekday", value: "true" }

- name: Set night light settings
  become_user: will
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value}}"
  with_items:
    - { key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled", value: "true" }
    - { key: "/org/gnome/settings-daemon/plugins/color/night-light-schedule-from", value: "21.5" }
    - { key: "/org/gnome/settings-daemon/plugins/color/night-light-schedule-to", value: "06" }
    - { key: "/org/gnome/settings-daemon/plugins/color/night-light-temperature", value: "2000" }

- name: Change alt-tab grouping
  become_user: will
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value}}"
  with_items:
    - { key: "/org/gnome/settings-daemon/plguins/media-keys/custom-keybindings/custom2/binding", value: "'<Alt>Tab'" }
    - { key: "/org/gnome/settings-daemon/plguins/media-keys/custom-keybindings/custom2/command", value: "switch-applications" }
    - { key: "/org/gnome/settings-daemon/plguins/media-keys/custom-keybindings/custom2/name", value: "Alt Tab ungrouping" }

- name: Change favorite apps
  become_user: will
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['firefox.desktop', 'chromium.desktop', 'org.gnome.Nautilus.desktop', 'nvim.desktop', 'terminator.desktop', 'org.manjaro.pamac.manager.desktop', 'calamares.desktop', 'manjaro-architect.desktop']"

# Can't find an easy way to do this via terminal
- name: Reminder for default programs
  become_user: will
  lineinfile:
    path: "/home/will/reminder.txt"
    line: "change default programs"
    create: yes
