# TODO: Make this not be hardcoded for manjaro laptop, this is supposed to work on e.g. Ubuntu server as well, need var file with package names

# Desktop Environments
- import_tasks: desktopenv/gnome/gnome.yml
  #when: gnome == true

# Install software
- import_tasks: software/install.yml

# Remove software
- import_tasks: software/remove.yml

# Perform rest of system setup
- import_tasks: setup/setup.yml
