- name: Install pip (Ubuntu)
  package:
    name: python3-pip
    state: latest

- name: Install psutil (Ubuntu)
  pip:
    name: psutil
    state: latest


- name: Install my utilities
  package:
    state: latest
    name:
      - neofetch
      - neovim
      - tmux
      - exa
      - bat
      - ripgrep
      - "{{ tealdeer }}"
      - zoxide
      - "{{ bottom }}"
      - "{{ du_dust }}"
      - "{{ mcfly }}"

- name: Install man pages (Arch)
  pacman:
    state: latest
    name:
      - man-db
      - man-pages
  when: ansible_distribution == "Archlinux"
