- name: Remove tldr
  package:
    name: tldr
    state: absent

- name: Install my utilities
  package:
    state: latest
    name:
      - neofetch
      - neovim
      - tmux
      - exa
      - bat
      - ripgrep
      - "{{ tealdeer }}"
      - "{{ zoxide }}"
      - "{{ bottom }}"
      - "{{ du_dust }}"
      - "{{ mcfly }}"
      - "{{ psutil }}"

- name: Install man pages (Arch)
  pacman:
    state: latest
    name:
      - man-db
      - man-pages
  when: ansible_distribution == "Archlinux"

- name: Symlink python to python3 (SUSE)
  command: ln -fs /usr/bin/python3 /usr/bin/python
  when: ansible_distribution == "openSUSE Tumbleweed"
