- name: Install my utilities
  package:
    state: latest
    name:
      - neofetch
      - neovim
      - tmux
      - ncdu
      - trash-cli
      - exa
      - bat
      - ripgrep
      - dust
      - duf
      - broot
      - fd
      - bottom
      - sd
      - tealdeer
      - gping
      - procs
