- name: List mirrors by speed (Manjaro)
  command: pacman-mirrors --fasttrack
  #when: ansible_distribution in ["Manjaro Linux"]

- name: Update repos and upgrade system (Manjaro)
  pacman:
    update_cache: yes
    upgrade: yes
  #when: ansible_distribution in ["Manjaro Linux"]
