- name: Get pacman mirrors modified time (Manjaro)
  stat:
    path: /etc/pacman.d/mirrorlist
  register: mirrorStats
  when: ansible_distribution == "Archlinux"

- name: Debug
  debug:
    var="{{ 4 - 3 }}"

# Compare current time epoch and the last modified time to only run when time difference more than 432000 seconds, 5 days
- name: List mirrors by speed (Manjaro)
  command: pacman-mirrors --continent
  when: (ansible_distribution == "Archlinux") #and (ansible_date_time.epoch - mirrorStats.stat.mtime > 432000)

- name: Update repos and upgrade system (Manjaro)
  pacman:
    update_cache: yes
    upgrade: yes
  when: ansible_distribution == "Archlinux"

#TODO:
# Not super easy, requires changing of /etc/apt/sources.list file using some regex to grab ubuntu version name
#- name: List mirrors by speed (Debian)
#  command: 
#  when: ansible_distribution == "Debian"

- name: Update repos and upgrade system (Debian)
  apt:
    update_cache: yes
    upgrade: yes
  when: ansible_distribution == "Debian"
