- name: List mirrors by speed (Manjaro)
  command: pacman-mirrors --continent
  when: ansible_distribution == "Archlinux"

- name: Update repos and upgrade system (Manjaro)
  pacman:
    update_cache: yes
    upgrade: yes
  when: ansible_distribution == "Archlinux"

#TODO:
# Not super easy, requires changing of /etc/apt/sources.list file using some regex to grab ubuntu version name
#- name: List mirrors by speed (Debian)
#  command: 
#  when: ansible_distribution == "Debian"

- name: Update repos and upgrade system (Debian)
  apt:
    update_cache: yes
    upgrade: yes
  when: ansible_distribution == "Debian"
