- name: Install chromium
  package:
    name: chromium
    state: latest

- name: Install flatpak
  package:
    name: flatpak
    state: latest

- name: Enable flathub
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: Install brave
  flatpak:
    name: com.brave.Browser
    state: present

- name: Install codium
  flatpak:
    name: com.vscodium.codium
    state: present

- name: Install bitwarden
  flatpak:
    name: com.bitwarden.desktop
    state: present
