- name: Edu-Roam Reminder
  become_user: will
  lineinfile:
    path: "/home/will/edu-roam-reminder"
    line: "setup edu roam kth"

- name: Grab auto-cpufreq
  become_user: will
  git:
    repo: "https://github.com/AdnanHodzic/auto-cpufreq.git"
    dest: "/home/will/auto-cpufreq"

- name: Auto-cpufreq reminder
  become_user: will
  lineinfile:
    path: "/home/will/auto-cpufreq-reminder"
    line: "setup auto cpufreq from the folder by running sudo ./auto-cpufreq-installer"

- name: Disable bluetooth on startup
  service:
    name: bluetooth
    enabled: no

# theme installed programs
# terminator, gnome terminal, code
