- name: Edu-Roam Reminder
  become_user: will
  lineinfile:
    path: "/home/will/reminder.txt"
    line: "setup edu roam kth"
    create: yes

- name: Grab auto-cpufreq
  git:
    repo: "https://github.com/AdnanHodzic/auto-cpufreq.git"
    dest: "/home/will/auto-cpufreq"

- name: Auto-cpufreq reminder
  become_user: will
  lineinfile:
    path: "/home/will/reminder.txt"
    line: "setup auto cpufreq from the folder by running sudo ./auto-cpufreq-installer"
    create: yes

- name: Disable bluetooth on startup
  service:
    name: bluetooth
    enabled: no

- name: Disable waitonline service
  service:
    name: NetworkManager-wait-online
    enabled: no

- import_tasks: shellConfig.yml
- import_tasks: swap.yml
