- name: Install ZSH
  package:
    name: zsh
    state: latest

- name: Change shell to ZSH
  user:
    name: will
    shell: /bin/zsh

- name: Get oh-my-zsh
  become_user: will
  command: wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh

- name: Install oh-my-zsh
  become_user: will
  shell:
    cmd: chmod +x ./install.sh && ./install.sh
  args:
    creates: /home/will/.oh-my-zsh

- name: Remove install.sh
  file:
    state: absent
    path: ./install.sh

- name: Get powerlevel10k
  become_user: will
  command: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git /home/will/.oh-my-zsh/custom/themes/powerlevel10k
  args:
    creates: /home/will/.oh-my-zsh/custom/themes/powerlevel10k

- name: Change zshrc to use p10k
  lineinfile:
    path: /home/will/.zshrc
    regexp: '^ZSH_THEME='
    line: ZSH_THEME="powerlevel10k/powerlevel10k"
