- name: Install Firefox
  package:
    name: firefox
    state: latest

- name: Install Celluloid
  package:
    name: celluloid
    state: latest
  when: ansible_distribution not in ["Fedora"]

- name: Install Deja Dup Backups
  package:
    name: deja-dup
    state: latest

- name: Reminder Deja Dup
  become_user: will
  lineinfile:
    path: "/home/will/reminder.txt"
    line: "Setup deja dup backup"
    create: yes

- name: Install Terminator
  package:
    name: terminator
    state: latest

- name: Install Texmaker
  package:
    name: texmaker
    state: latest

- name: Install Libre Office
  package:
    name: libreoffice
    state: latest

- name: Anki text reminder
  become_user: will
  lineinfile:
    path: "/home/will/reminder.txt"
    line: "fix anki"
    create: yes

- name: Install yt-dlp
  package:
    name: yt-dlp
    state: latest

- name: Install Eye of Gnome
  package:
    name: eog
    state: latest

# Some programs use things like flatpaks on some distros
# So we need independent install procedures for those distros
- import_tasks: arch/install.yml
  when: ansible_distribution == "Archlinux"

- import_tasks: suse/install.yml
  when: ansible_distribution == "openSUSE Tumbleweed"

- import_tasks: ubuntu/install.yml
  when: ansible_distribution == "Ubuntu"

- import_tasks: fedora/install.yml
  when: ansible_distribution == "Fedora"

# Install Codium extensions
- import_tasks: codeExtensions.yml
