- name: Install Firefox
  package:
    name: firefox
    state: latest

- name: Install Chromium
  package:
    name: chromium
    state: latest

- name: Install Brave
  package:
    name: brave-browser
    state: latest

- name: Install Bitwarden
  package:
    name: bitwarden
    state: latest

- name: Install Celluloid
  package:
    name: celluloid
    state: latest

- name: Install Code OSS
  package:
    name: code
    state: latest

- name: Install Code OSS Extensions
  import_tasks: codeExtensions.yml

- name: Install Deja Dup Backups
  package:
    name: deja-dup
    state: latest

- name: Reminder Deja Dup
  become_user: will
  lineinfile:
    path: "/home/will/reminder.txt"
    line: "Setup deja dup backup"
    create: yes

- name: Install Timeshift
  package:
    name: timeshift
    state: latest

- name: Reminder Timeshift
  become_user: will
  lineinfile:
    path: "/home/will/reminder.txt"
    line: "setup timeshift"
    create: yes

- name: Install Terminator
  package:
    name: terminator
    state: latest

- name: Install Texmaker
  package:
    name: texmaker
    state: latest

- name: Install Libre Office
  package:
    name: libreoffice
    state: latest

- name: Install Obsidian
  package:
    name: obsidian
    state: latest

- name: Anki text reminder
  become_user: will
  lineinfile:
    path: "/home/will/reminder.txt"
    line: "fix anki"
    create: yes

- name: Install yt-dlp
  package:
    name: yt-dlp
    state: latest

- name: Install Eye of Gnome
  package:
    name: eog
    state: latest

- name: Install Ranger
  package:
    name: ranger
    state: latest

- name: Install Make
  package:
    name: make
    state: latest
