- name: Install Firefox
  package:
    name: firefox
    state: latest

- name: Install Chromium
  package:
    name: chromium
    state: latest

- name: Install Bitwarden
  package:
    name: bitwarden
    state: latest

- name: Install Celluloid
  package:
    name: celluloid
    state: latest

#TODO: Install extensions and settings
- name: Install Code OSS
  package:
    name: code
    state: latest

- name: Install Deja Dup Backups
  package:
    name: deja-dup
    state: latest

- name: Reminder Deja Dup
  copy:
    dest: "/home/will/reminder-dejadup"
    content:
      "Setup deja dup backup"

- name: Install Timeshift
  package:
    name: timeshift
    state: latest

- name: Reminder Timeshift
  copy:
    dest: "/home/will/reminder-timeshift"
    content:
      "setup timeshift"

- name: Install Terminator
  package:
    name: terminator
    state: latest

- name: Install Texmaker
  package:
    name: texmaker
    state: latest

- name: Install Libre Office
  package:
    name: libreoffice
    state: latest

- name: Anki text reminder
  copy:
    dest: "/home/will/reminder-anki"
    content:
      "fix anki and remember --nosandbox but should be zsh aliased already"

- name: Install yt-dlp
  package:
    name: yt-dlp
    state: latest

- name: Install Eye of Gnome
  package:
    name: eog
    state: latest

- name: Install Ranger
  package:
    name: ranger
    state: latest

- name: Install Make
  package:
    name: make
    state: latest
